os_type: centos
os_version: 8.3
flavor: crimson
roles:
- - mon.a
  - mon.b
  - mon.c
  - mgr.x
  - osd.0
  - osd.1
  - osd.2
openstack:
  - volumes: # attached to each instance
      count: 3
      size: 10 # GB
tasks:
- install:
    flavor: crimson
    ceph:
        flavor: crimson
- ceph:
    flavor: crimson
    conf:
      osd:
        osd shutdown pgref assert: true
      global:
        ms cluster mode: crc
        ms service mode: crc
        ms client mode: crc
        ms mon service mode: crc
        ms mon cluster mode: crc
        ms mon client mode: crc
        osd pool default min size : 1
    pre-mgr-commands:
      - sudo ceph config set mgr mgr_pool false --force
    log-ignorelist:
      - objects unfound and apparently lost
      - overall HEALTH_
      - \(OSDMAP_FLAGS\)
      - \(OSD_
      - \(PG_
- peer:
