os_type: centos
os_version: 8.3
flavor: crimson
roles:
- - mon.a
  - mgr.x
  - osd.0
  - osd.1
  - osd.2
  - osd.3
  - client.0
- - mon.b
  - mon.c
  - osd.4
  - osd.5
  - osd.6
  - osd.7
openstack:
  - volumes: # attached to each instance
      count: 4
      size: 10 # GB
tasks:
- install:
    flavor: crimson
    ceph:
        flavor: crimson
- ceph:
    flavor: crimson
    create_rbd_pool: false
    pre-mgr-commands:
      - sudo ceph config set mgr mgr_pool false --force
    log-ignorelist:
      - overall HEALTH_
      - \(OSDMAP_FLAGS\)
      - \(OSD_
      - \(PG_
      - \(POOL_
      - \(CACHE_POOL_
      - \(OBJECT_
      - \(SLOW_OPS\)
      - \(REQUEST_SLOW\)
      - \(TOO_FEW_PGS\)
      - slow request
    conf:
      osd:
        osd shutdown pgref assert: true
      global:
        ms cluster mode: crc
        ms service mode: crc
        ms client mode: crc
        ms mon service mode: crc
        ms mon cluster mode: crc
        ms mon client mode: crc
- workunit:
    clients:
      all:
        - mon/pg_autoscaler.sh
