overrides:
  ceph:
    log-ignorelist:
    - \(POOL_APP_NOT_ENABLED\)
    conf:
      global:
        enable experimental unrecoverable data corrupting features: crimson
        bluestore throttle deferred bytes: 0
      mon:
        osd pool default crimson: true
      osd:
        crimson seastar smp: 3
    flavor: crimson
  workunit:
    env:
      CRIMSON_COMPAT: '1'
