overrides:
  ceph:
    log-ignorelist:
    - \(POOL_APP_NOT_ENABLED\)
    conf:
      global:
        enable experimental unrecoverable data corrupting features: crimson
      mon:
        osd pool default crimson: true
      osd:
        crimson osd obc lru size: 10
      mgr:
        mgr stats period: 30
    flavor: crimson
  workunit:
    env:
      CRIMSON_COMPAT: '1'
  ansible.cephlab:
        repo: https://github.com/VallariAg/ceph-cm-ansible.git
        branch: wip-remove-get_md5
