overrides:
  tasks:
  - install:
      exclude_packages:
        - cephfs-java
  - print: "**** cephfs-java is excluded"
  ceph:
    conf:
      global:
        enable experimental unrecoverable data corrupting features: crimson
      mon:
        osd pool default crimson: true
    flavor: crimson
  workunit:
    env:
      CRIMSON_COMPAT: '1'
