overrides:
  ceph:
    pre-mgr-commands:
      - sudo ceph config set mgr mgr_pool false --force
    log-ignorelist:
    - Reduced data availability
    - OSD_.*DOWN
    - \(RECENT_CRASH\)
    - reached quota
    - but it is still running
    - overall HEALTH_
    - \(POOL_FULL\)
    - \(SMALLER_PGP_NUM\)
    - \(CACHE_POOL_NO_HIT_SET\)
    - \(CACHE_POOL_NEAR_FULL\)
    - \(POOL_APP_NOT_ENABLED\)
    - \(PG_AVAILABILITY\)
    - \(PG_DEGRADED\)
    conf:
      client:
        debug ms: 1
      mon:
        mon warn on pool no app: false
      osd:
        osd class load list: "*"
        osd class default list: "*"
tasks:
- workunit:
    clients:
      client.0:
        - rados/test-crash.sh
- ceph.restart: [osd.*]
- exec:
    mon.a:
      -find $TESTDIR/archive/coredump -type f -exec rm -f {} \;
